### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by washington93** [fl4m3x/be-the-hero#2]
Bom dia, 

Realizei o "git clone" e dentro do diretório "backend" dei "npm start", porém aparece o seguinte erro.

> internal/modules/cjs/loader.js:985
>   throw err;
>   ^
> 
> Error: Cannot find module '../utils/generateUniqueId'
> Require stack:
> - C:\Users\Washington\Desktop\GitProjects\be-the-hero\backend\src\controllers\OngController.js
> - C:\Users\Washington\Desktop\GitProjects\be-the-hero\backend\src\routes.js
> - C:\Users\Washington\Desktop\GitProjects\be-the-hero\backend\src\index.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
>     at Module.require (internal/modules/cjs/loader.js:1044:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (C:\Users\Washington\Desktop\GitProjects\be-the-hero\backend\src\controllers\OngController.js:3:26)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Module.load (internal/modules/cjs/loader.js:1002:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>     at Module.require (internal/modules/cjs/loader.js:1044:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\Washington\\Desktop\\GitProjects\\be-the-hero\\backend\\src\\controllers\\OngController.js',
>     'C:\\Users\\Washington\\Desktop\\GitProjects\\be-the-hero\\backend\\src\\routes.js',
>     'C:\\Users\\Washington\\Desktop\\GitProjects\\be-the-hero\\backend\\src\\index.js'
>   ]
> }
> **[nodemon] app crashed - waiting for file changes before starting...**

**Comment by fl4m3x** [comment]
Opa! Irei estar fazendo alguumas alterações e irei corrigir isso, @washington93. Fique ligado que, no máximo amanhã pela manhã, o repo será atualizado. =D

**Comment by fl4m3x** [comment]
Opa @washington93! Finalizei e aqui está tudo tranquilo agora! Dá uma olhada aí meu bom! =D

**Comment by washington93** [comment]
Muito obrigado @fl4m3x . Testei aqui e rodou legal. 

Aproveitando. Me tira uma dúvida de iniciante no git... Quando eu for dar o "git clone" com o intuito de contribuir para o seu projeto devo clonar do repositório que fiz o Fork e ficou no meu profile, ou do seu?

**Comment by fl4m3x** [comment]
então, o fork que está no seu perfil é o mesmo que está aqui. Então tanto o fork quanto o do meu perfil são idênticos. 😄 fique a vontade para contribuir com o projeto, pretendo implementar novas funcionalidades no futuro, sinta-se a vontade para contribuir com isso! 👍
