### ISSUE TITLE
Alterar Insident

### ISSUE THREAD

**Issue by aguedes2** [fl4m3x/be-the-hero#3]
Olá pessoal eu pensei em uma funcionalidade para alterar o incident no frontend. Clica no incident, vai para uma tela semelhante ao cadastro, entretanto com os campos já preenchidos com os dados do incident, o adm apenas alterar 1 ou mais campos que deseja e clica em salvar.

Eu criei uma rota no backend com o método PUT, e pensei em passar os dados do incident para a página do formulário e inserir nos inputs os dados do incident.

**Comment by fl4m3x** [comment]
Rapaz, é uma ótima ideia! =D

**Comment by fl4m3x** [comment]
Feito! Valeu! =D
